### ISSUE TITLE
`show` more info

### ISSUE THREAD

**Issue by lolilolicon** [mvdan/fdroidcl#11]
First, I'd like to request `<permissions>` and `<nativecode>` be added to the output of `show`.

Second, is "Name" a typo for "Version" in the "Available Versions" section?

**Comment by mvdan** [comment]
> First, I'd like to request <permissions> and <nativecode> be added to the output of show.

This is similar to what I said in another issue about lines per item - if I add more information per apk, listing all apks will just be too much to scroll through. Not sure what to do about this.

> Second, is "Name" a typo for "Version" in the "Available Versions" section?

Not a typo, but `Version` is definitely better since we're showing both the version name and the version code.

**Comment by lolilolicon** [comment]
I don't think we should care about the size of the output in the case of `show` -- it already outputs a lot of lines; e.g. I personally expect that and usually pipe it to `less`.

Or, how about a switch for tweaking verbosity? `show -v` can show more than normal `show`.

**Comment by mvdan** [comment]
> I don't think we should care about the size of the output in the case of show -- it already outputs a lot of lines; e.g. I personally expect that and usually pipe it to less.

That's a good point.

> Or, how about a switch for tweaking verbosity? show -v can show more than normal show.

Not a fan of that because it's a very thin line. What is and what isn't verbose? etc.

**Comment by lolilolicon** [comment]
Indeed it's a thin line. So just add them, agreed? ;)

**Comment by mvdan** [comment]
@lolilolicon this is the easiest to fix of the issues you opened, so I'll leave it for you. The data is there, you just need to add some prints.
