### ISSUE TITLE
Any way to list available categories?

### ISSUE THREAD

**Issue by lolilolicon** [mvdan/fdroidcl#12]
If not, perhaps make `search -c` or/and `search -c \?` do it?

**Comment by mvdan** [comment]
`-c` always takes an argument, and having an arbitrary string trigger this like `?` would be confusing.

I'm thinking that we could have `fdroidcl categories` instead. Having something like `fdroid list categories` doesn't make too much sense as there are no other things to list IMO.

**Comment by lolilolicon** [comment]
Hey I was just thinking. How about `list packages` too, to list the app ids, which is useful for zsh completion for `show`.

**Comment by mvdan** [comment]
> Hey I was just thinking.

Me too, hence why I'm throwing ideas at this :)

> How about list packages too, to list the app ids, which is useful for zsh completion for show.

Good point. Let's come up with a list of things to aggregate:

* appids
* categories
* licenses

**Comment by lolilolicon** [comment]
I think that's pretty much it :100:
In case anything is missing, they can be added later, too :)

**Comment by mvdan** [comment]
Maybe I should move devices here too, i.e. `fdroidcl list devices` instead of `fdroidcl devices`. Then the listing would not be limited to what's on the index, so we could do `fdroidcl list repos` too.

**Comment by mvdan** [comment]
Hmm, but these two would do more than printing a word per line. So probably not a good idea.

**Comment by lolilolicon** [comment]
Well for these, how about `list -v` for verbose...

**Comment by mvdan** [comment]
FYI, patches are welcome. I'll probably get to doing all of these at some point, but if you could help that'd be great.

**Comment by lolilolicon** [comment]
Would love to, but I don't know go man...

**Comment by mvdan** [comment]
If you know Java, Python or even some C, it should be easy to send small patches :)

**Comment by lolilolicon** [comment]
I can try, thanks for the encouragement.

**Comment by lolilolicon** [comment]
For list of categories and licenses, since there aren't many of them, we can cache them to disk on `update`. Later on we can simply load the cache rather than parsing the whole db all over again.

This will allow for example to report immediately `No such category` for `search -c Porn` #14

**Comment by mvdan** [comment]
> For list of categories and licenses, since there aren't many of them, we can cache them to disk on update. Later on we can simply load the cache rather than parsing the whole db all over again.

I don't think this is worth it. Filtering by - or accumulating - categories or licenses is linear time over an in-memory database. I doubt it will take any more than a few milliseconds.

**Comment by lolilolicon** [comment]
Well yes, it should be fast, we'll see when the list commands are written
(by not me :)

> I want to list categories fast so zsh completion will feel snappy :)

**Comment by mvdan** [comment]
I'll write it this way, you tell me if running the whole thing is slow.

**Comment by mvdan** [comment]
Actually, I forgot that `list packages` is already done: `search -q`.

**Comment by lolilolicon** [comment]
Yes, but it does some unnecessary work...

**Comment by mvdan** [comment]
What unnecessary work?

**Comment by lolilolicon** [comment]
the work in `filterAppsSearch`

**Comment by lolilolicon** [comment]
Actually there's no need to read the code; `list packages` should not be as slow as `search -q` is right now. I *suppose* it should be at least as fast as `grep "<id>" db.xml | sort`.

**Comment by mvdan** [comment]
Right - I should have a special case for no search terms.

**Comment by mvdan** [comment]
Actually, reading the xml from the cache is turning out to be very slow. I should probably cache the metadata in an internal format.

**Comment by lolilolicon** [comment]
Hey this discussion bears fruit :)

**Comment by mvdan** [comment]
I never intended this tool to be used this way, so startup time was never something I looked into. 300ms (on my machine) is fine for interactive use, but not for something like shell completion.

**Comment by mvdan** [comment]
@lolilolicon `fdroid search -q` now takes around 30ms on my machine.

**Comment by lolilolicon** [comment]
Confirmed, it's snappy. The cache does work nicely.
