### ISSUE TITLE
Show & filter by last updated in `search` results

### ISSUE THREAD

**Issue by lolilolicon** [mvdan/fdroidcl#13]
I like to use `search -o updated` to search for actively maintained apps, but
currently there's no way to tell just how recently any of them is updated.

From there I'd like to request,

* Show last updated date in `search` results. `yyyy-mm-dd` or `<n> days` or `<n>d`.
* Filter apps by last updated date, e.g. `search -d 14` for last 14 days.
* Lastly, let's reverse the list so the newer come before the older.

Some of these may apply to "added", too.

**Comment by mvdan** [comment]
> Show last updated date in search results

Disagree - the point is to make each item take as less lines as possible. Otherwise, only a few apps would fit in a screen. The Android client doesn't do this either.

> Filter apps by last updated date, e.g. search -d 14 for last 14 days.

Sounds good.

> Lastly, let's reverse the list so the newer come before the older.

Hm. I find the current one best, since the last ones to be output is what I see in the terminal. Otherwise I would do something like `head` or `less` on the output.

The consensus is to go from smaller to greater, which is what is done now for dates. If we were outputting a single line per app you could do `tac` to get the reverse, but unfortunately we don't.

**Comment by lolilolicon** [comment]
> I find the current one best, since the last ones to be output is what I see in the terminal.
You're right. I was thinking of a LOT of results which I tend to pipe to `less` followed by pressing G. Disregard this point.

> Disagree - the point is to make each item take as less lines as possible. Otherwise, only a few apps would fit in a screen.

Well, appending `12d` doesn't take too much screen real estate though...

> The Android client doesn't do this either.
But we aren't too satisfied by the Android client either, hence fdroidcl ;)

I'm glad you agree with the filtering idea :)

**Comment by mvdan** [comment]
> Well, appending 12d doesn't take too much screen real estate though...

In a new line? It does. If not in a new line, where?

> But we aren't too satisfied by the Android client either, hence fdroidcl ;)

Given that I develop both, this is not my reasoning :) they just serve different purposes.

**Comment by lolilolicon** [comment]
I'd say just append it after the version.

**Comment by mvdan** [comment]
> I'd say just append it after the version.

If you do `fdroidcl search`, you'll see that we already take quite a number of columns.

**Comment by lolilolicon** [comment]
Well, then append to the summary line. They're usually much shorter than the line above.

**Comment by lolilolicon** [comment]
Another related idea I mean to propose is to allow format strings or some template for the output of `search`. This can be useful for scripting, especially.
For example, `search -f "https://f-droid.org/repository/browse/?fdid=%i\n"`.
This requires thinking of mapping of format strings to tags in the XML...
Alternatively, something like `%{id}` `%{lastupated}` would be free of such burdens. (This is in imitation of the `curl -w` option.)

This is a lot to ask & of course you're free to not do anything. Just ideas.

**Comment by mvdan** [comment]
I think this is out of scope. If anyone needs such fine-grained access to the data, they should just use the `index.xml` directly. This is an app, not a library. The library itself (`github.com/mvdan/fdroidcl`) just parses the data and makes it available.

**Comment by lolilolicon** [comment]
Point taken. Thanks for the clarification.
