### ISSUE TITLE
Wrong diagnosis for no results found when -c is passed to `search`

### ISSUE THREAD

**Issue by lolilolicon** [mvdan/fdroidcl#14]
```
$ fdroidcl search unmentionable
$ fdroidcl search -c Time unmentionable
No such category: Time
Usage: fdroidcl search [<regexp...>] [-h]

Available options:
  -c string
    	Filter apps by category
  -i	Filter installed apps
  -o string
    	Sort order (added, updated)
  -q	Print package names only
  -u	Filter apps with updates
```
The error is there is a category "Time".

**Comment by mvdan** [comment]
Ah, nice catch.

**Comment by lolilolicon** [comment]
Not really fixed...

    $ fdroidcl search -q texteditor
    fr.xgouchet.texteditor
    $ fdroidcl search -q -c Connectivity texteditor
    No such category: Connectivity

**Comment by mvdan** [comment]
> Not really fixed...

Oh, that's a slightly different case than the one you mentioned.

Yes, as you say, we should report better error messages.

**Comment by lolilolicon** [comment]
This one is pretty subtle...

**Comment by mvdan** [comment]
@lolilolicon want to tag 0.3.0, any other issues/patches from you?

**Comment by lolilolicon** [comment]
Nope, we fine for now

**Comment by mvdan** [comment]
0.3.0 released :)
