### ISSUE TITLE
Add a way to update all installed apps

### ISSUE THREAD

**Issue by ian-kelling** [mvdan/fdroidcl#22]
Currently you can do it with a script, such as https://iankelling.org/git/?p=fdroidcl-up;a=blob;f=fdroidcl-up;hb=HEAD

**Comment by mvdan** [comment]
So you're thinking of something like `fdroidcl upgrade -a`?

Also, FYI, this can now be done via `fdroidcl upgrade $(fdroidcl search -q -u)`. But I understand that it's more cumbersome and could be a bit slower to start up.

**Comment by ian-kelling** [comment]
> So you're thinking of something like fdroidcl upgrade -a?

Yup.

> Also, FYI, this can now be done via fdroidcl upgrade $(fdroidcl search -q -u). But I understand that it's more cumbersome and could be a bit slower to start up.

Good to know. I suppose this would mostly help to make it a bit easier to figure out.

**Comment by mvdan** [comment]
Actually, if we make `fdroidcl install foo bar` also do upgrades, I'm thinking that `fdroidcl upgrade` should just upgrade everything and not take any arguments.

Or, alternatively, `fdroidcl upgrade` with no args would upgrade everything, and `fdroidcl upgrade foo bar` would only upgrade `foo` and `bar`.

If you'd like to submit a patch, I'd be happy to review.

**Comment by ian-kelling** [comment]
Oh, yes, that makes sense. I probably won't get to making a patch in the next week or two at least, so feel free to work on this.

**Comment by mvdan** [comment]
I'm lacking of free time at the moment, so I don't plan on working on this in the near future (~weeks). That's why I've added the help wanted labels.

**Comment by mvdan** [comment]
Now that #23 is fixed, one can do this very easily:

    fdroidcl install $(fdroidcl search -u -q)

I'm tempted to not add a feature for this. Since we removed `upgrade`, it would probably be `fdroid install -u`. Feedback welcome.

**Comment by mvdan** [comment]
This is now done - try `fdroidcl install -u`.
