### ISSUE TITLE
Add a way to install a list of apps if they are not already installed

### ISSUE THREAD

**Issue by ian-kelling** [mvdan/fdroidcl#23]
Currently you can do it with a script, such as https://iankelling.org/git/?p=fdroidcl-up;a=blob;f=fdroidcl-up;hb=HEAD

**Comment by mvdan** [comment]
Just so I understand, this is about giving `fdroidcl` a list of packages to install only if they're not already installed. What about those that are already installed? Should it upgrade them if upgradeable or just skip them?

**Comment by mvdan** [comment]
Have you tried using `fdroidcl install` on such a list? I'm not sure what it would do right now.

**Comment by ian-kelling** [comment]
> Have you tried using fdroidcl install on such a list?

Right now, it will install a list if none in the list are currently installed. If any are already installed, it reports that it's already installed and does exit 1 without installing anything. 

> Should it upgrade them if upgradeable or just skip them?

Either one would be acceptable. If we just modified the current install command, I'd probably have it work like apt in debian and do an upgrade if upgradable.

**Comment by mvdan** [comment]
> do an upgrade if upgradable.

Agreed. Happy to review a PR if you'd like to work on the patch - should be an easy one.

**Comment by gsantner** [comment]
I would suggest a method that just does the job - installing the latest version - doesn't matter if already installed or not. And this one could be called in e.g. a loop - for each package id

**Comment by mvdan** [comment]
Actually, I'm not sure why we have *both* an install and an upgrade command. It should just be called `install`, and it should either install or upgrade the specified or latest version as appropriate.
