### ISSUE TITLE
F-Droid package request

### ISSUE THREAD

**Issue by davidhedlund** [mvdan/fdroidcl#25]
```* [ x] The original app author has been notified (and supports the inclusion).``` - https://gitlab.com/fdroid/rfp/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D=

* Are you ok with this (this comment will be used as reference)?

* Are you willing to packagefdroidcl to F-Droid yourself?

**Comment by davidhedlund** [comment]
```* [ x] The original app author has been notified (and supports the inclusion).``` - https://gitlab.com/fdroid/rfp/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D=

Are you ok with this (this comment will be used as reference)?

**Comment by mvdan** [comment]
I think you're confused. This is not an Android app. Even though you could get a binary to run on a linux phone, it would be of little use given that this has no graphical UI.

**Comment by davidhedlund** [comment]
@mvdan Thank you for pointing this out.

**Comment by davidhedlund** [comment]
@mvdan Can you please state that fdroidcl is for GNU/Linux but not for Android on https://github.com/mvdan/fdroidcl?

**Comment by mvdan** [comment]
That would be false; it's supported on any platform that Go runs on, including Mac, Windows and Linux.

Note how I didn't write GNU/Linux. As said, this program should be able to run on Android. But nowhere is it said that it is an app with a GUI.

**Comment by davidhedlund** [comment]
Ok. Now I understand.
