### ISSUE TITLE
TLS handshake timeouts

### ISSUE THREAD

**Issue by AnarchieHandy** [mvdan/fdroidcl#27]
Hey bro, I often get TLS handshake timeouts on repo download and sometimes on apps downloads. Looks somewhat like this:
`Downloading https://f-droid.org/repo/index.jar... 
update: could not update index: Get https://f-droid.org/repo/index.jar: net/http: TLS handshake timeout`
and this:
`Downloading https://f-droid.org/repo/cz.martykan.forecastie_14.apk... 
install: could not download cz.martykan.forecastie: Get https://f-droid.org/repo/cz.martykan.forecastie_14.apk: net/http: TLS handshake timeout`
I would guess that this is related to the overall slowness of the fdroid servers. Maybe it's enough to increase the timeout times?

**Comment by mvdan** [comment]
The default is 10 seconds in Go - I assume that's what you're hitting.

I'm inclined to leave it as the default - as you say, it's rather a problem with the servers. 10 seconds seems like plenty to me. Even if I doubled it, we could always make the point to double it again.

Could you try again tomorrow, and see if the servers are behaving?

Out of curiosity, does the HTTPS site load fine on a browser?

**Comment by AnarchieHandy** [comment]
The https site loads fine, yes. 
I have noticed the slowness of the servers for years already, I don't think anything is going to happen there ;) but it's just a repo and doesn't really need to be fast, so I guess that's okay. You can check out the time it takes for the android client to update the repos. Before the download even begins the notification shows something like 'preparing download' for more than 10s sometimes. Maybe it is the TLS handshake?
Otherwise, do you know how I could implement some sort of 'repeat if unsuccessful' in a shell script? ;)

**Comment by mvdan** [comment]
Are you building for source? If so, could you try bumping the HTTP or TLS timeouts and see if that fixes it?

If you don't know how to do the change in Go, I can create a branch for it and ask you to build and try it.

**Comment by AnarchieHandy** [comment]
Unfortunately, I don't know how to do any of these things... but with some instructions I would absolutely build and try it :)

**Comment by AnarchieHandy** [comment]
Ok bro, I just made a little workaround for my script... using something like this:
`if [ -z $(adb shell pm list packages de.grobox.liberario) ]; then fdroidcl install ...`
Don't know how I could check if the `fdroidcl update` worked though...

**Comment by mvdan** [comment]
Sorry for the late reply. Please see https://gitlab.com/fdroid/admin/issues/35.

It seems like a server issue and affecting all sorts of clients. I'm inclined to wait another week or so, to see if it's fixed upstream before bginging up the timeouts.

**Comment by amo13** [comment]
Oh, good hint! Yes, waiting seems reasonable for now, you're right!

**Comment by mvdan** [comment]
This seems to have gone away on its own somehow. In any case, follow that thread for updates from the people who run the site and repo.
