### ISSUE TITLE
Hardware compatibility check

### ISSUE THREAD

**Issue by oimaasi** [mvdan/fdroidcl#29]
I know there is no hardware compatibility check at the moment. But may I ask how to check it manually? With the f-droid app on my phone, it will show compatibility. Is it possible to get this information with something like `fdroidcl show app-id`?

I have an old phone which runs a version lower than Android 4.4, so compatibility is a major issue.

**Comment by mvdan** [comment]
Note that the API level (android version) and ABI (hardware architecture) are both checked: https://github.com/mvdan/fdroidcl/blob/bda18064d61e91e82c7c645e52964e588f8527cc/index.go#L236

These are the two most common sources of app incompatibilities with devices, hence why they are supported. What the README refers to by "hardware compatibility" is hardware features of each device, such as the presence of a camera or a GPS device.

I'm sure there would be a way to retrieve that information from the device via `adb` - I just haven't implemented it. It's not a common source of issues either.

Is there a specific case where you have found a bug, or is this issue just a question?

**Comment by mvdan** [comment]
Timing out - I don't see anything we should do in the short term.
