### ISSUE TITLE
[ENH] auto completion for package names

### ISSUE THREAD

**Issue by jeythekey** [mvdan/fdroidcl#34]
Very practical tool, thanks. It would be really convenient, if there was auto-completion for the package names for the install command. (We already have them locally, right?)
The basic version would just complete the local pathnames, while an advanced version could suggest/extend full package names based on some pattern (i.e. not necessarily starting with com...., but more similar to the search command, thereby possibly not requiring that step anymore).
Or should auto-completion already work? (I'm using zsh.)

**Comment by mvdan** [comment]
Package name completion should already work on zsh; see https://github.com/mvdan/fdroidcl/blob/master/contrib/completion/zsh/_fdroidcl. You just have to make sure that the completion script is being set up correctly.

Though I'm not a Zsh user, so I don't directly maintain the script. Hence why it's under `contrib/`. If you find bugs, please send patches.

**Comment by mvdan** [comment]
I'll assume my comment above answers your question.
