### ISSUE TITLE
Automate installation

### ISSUE THREAD

**Issue by HumanG33k** [mvdan/fdroidcl#39]
- I have to deploy several times some lineage OS and a bunch of packages but time between install can be long.
- I start to make a simple bash script to automaticly install packages.

- I don’t know exactly the adb/android capabilities. (even if i have some good knowledge on GNU) 
- Some part of this post can be off-topic but it can help
- Some other existing tool may exist to do some part off the stuff

First when i do a :
```bash
fdroidcl devices 
```
A message to inform devices need adb activate can be a good remember.

it can be great if fdroidcl can automate as possible all the following process. 
- activate adb (i think it’s not possible for security reason)
- install f-droid.apk
- add some repository to fdroid
- configure fdroid 
- install need app (what fdroidcl do)
- configure apps (i know it depend on each app, maybe there is a configuration protocol ?)  

thx for your great job.

**Comment by mvdan** [comment]
> activate adb (i think it’s not possible for security reason)

Yes, that's not possible.

> install f-droid.apk
> add some repository to fdroid
> configure fdroid

This app is an *alternative* to the Android client, not a companion or "client" for it. We never interact with the Android client, and there isn't even a way to do that properly.

> configure apps (i know it depend on each app, maybe there is a configuration protocol ?)

This is out of scope too. If you really want to do this, I suggest to use app backups, which can contain app data such as settings and login information.

I'm not sure there's anything we can do with this issue overall. fdroidcl can be used as an F-Droid client, to install/update/remove apps, or to search for apps. Anything else is not in scope.

**Comment by HumanG33k** [comment]
Ok, 
Thx for the feedback. 
I knew some things were out of scope but i prefer ask. 
If i take the time to find what i need i will post here because i pretty sure i m not alone with this needed.

**Comment by mvdan** [comment]
Sure - if you find anything interesting, or have any specific feature requests or bugs, feel free to file them in this issue tracker. I'm closing this issue for now, because all that it contains is out of scope at the moment.
