### ISSUE TITLE
Possibility to add/remove repo

### ISSUE THREAD

**Issue by onny** [mvdan/fdroidcl#4]
See title.

Best regards,
Jonas

ps.
Thanks for this nice tool!

**Comment by mvdan** [comment]
This is already supported. Just not documented. Will add it to the README.

**Comment by onny** [comment]
This doesn't seem to work :(
````
{

    "repos": 

    {
        "ID": "Eutopia Experimental",
        "URL": "https://eutopia.cz/experimental/fdroid/repo",
        "Enabled": "true"
    }

}
````

**Comment by mvdan** [comment]
Why the capitalization? Have you looked at the default config?

And enabled is a bool, not a string.

**Comment by onny** [comment]
There is no default config.json file getting created :(
Using lower case key names doesn't solve the problem:
```
onny@onny ~/.config/fdroidcl % fdroidcl update
2016/03/16 11:39:35 Could not load config: could not decode config file: json: cannot unmarshal object into Go value of type []main.repo
2016/03/16 11:39:35 Using default config
Downloading https://f-droid.org/repo/index.jar... not modified
```

**Comment by mvdan** [comment]
My bad, you have to run `fdroidcl defaults`.

**Comment by onny** [comment]
Thanks that worked!
