### ISSUE TITLE
Publish this app as snap or deb

### ISSUE THREAD

**Issue by Mannshoch** [mvdan/fdroidcl#40]
Please publish this app as snap or deb for Ubuntu.

**Comment by mvdan** [comment]
Someone already added it to Debian years ago: https://packages.debian.org/buster/fdroidcl

It's also on Ubuntu, even 18.04. Is that not enough?

If someone wants to add a snap, I'm happy to add a link in the README, but I won't maintain that myself.

**Comment by Mannshoch** [comment]
😖 apt tells me I searched for fdroidctl instead of fdroidcl. sorry.

**Comment by mvdan** [comment]
No worries :) closing this as it's already done.

**Comment by fazlerabbi37** [comment]
@mvdan do you think the README file should document the Debian package, which of course would also include that it is an unofficial package?

**Comment by mvdan** [comment]
Sure. Feel free to send a PR with added README content, like we did under "packages are available" in https://github.com/mvdan/sh#shfmt.

**Comment by fazlerabbi37** [comment]
@mvdan I just created a PR. Do let me know if anything is needed, after you take a look.
