### ISSUE TITLE
Add option to list and uninstall all apps which are currently installed

### ISSUE THREAD

**Issue by Mannshoch** [mvdan/fdroidcl#42]
Please add a possibility to list [all apps](https://android.stackexchange.com/questions/90141/obtain-package-name-and-common-name-of-apps-via-adb) and uninstall all apps which are currently installed.

That would make this tool into a nice cleanup tool for new Phones because with adb you could do work you could not do from inside the phone.

**Comment by mvdan** [comment]
I'm not sure if I understand. When a phone comes preloaded with lots of apps, those are very often not possible to uninstall.

**Comment by Mannshoch** [comment]
With adb you are able to uninstall bloat ware that you could not on android.

**Comment by mvdan** [comment]
Clarify how? If it involves root in any way, I don't think that's something we want to get into.

**Comment by Mannshoch** [comment]
Because I will get a phone soon I wish to clean up, I checked many websites about how to. Everywhere they write that over adb you could remove every app even you do not have root with `pm uninstall --user 0 {package name}`

**Comment by mvdan** [comment]
I don't know, that seems like something not really related to an F-Droid client. If someone wants to write a program that lists preinstalled apps and tries to uninstall them all via adb, it should be possible to write that with a dozen lines of shell. I don't have a use for that myself, and honestly I would rather not write and maintain the code for someone else.

**Comment by Mannshoch** [comment]
I see some potential to do things other than normal f-droid. f-droid from ADB has other use cases than f-droid from app.
In my opinion it would perfectly fit into this app to manage all kind of software modification. f-droid in Android has the need to work also for normal users. F-droid from ADB is not an app for everyday use. In my opinion it is more a tool for Admins.

**Comment by mvdan** [comment]
I guess I could be open to others contributing code with tests for "power user" features like that. But I don't think this issue should remain open if noone steps up to that, as I don't intend to work on it myself, and I'm the only maintainer at the moment.

**Comment by Linus789** [comment]
Since no one stepped up, I’m going to close this issue.
