### ISSUE TITLE
Enhance reporting on failed upgrade

### ISSUE THREAD

**Issue by Mannshoch** [mvdan/fdroidcl#43]
I'm actually not able to upgrade DAVx5. fdroid only show   `install: could not install at.bitfire.davdroid: exit status 1`
Please show more details about the error.

**Comment by Mannshoch** [comment]
Found the cause of this Problem. My exit status 1 was created by the fact that Android made a storage warning. Even I have enough storage left for the Update, It does not work.

**Comment by Linus789** [comment]
Should now work with [v0.7.0](https://github.com/mvdan/fdroidcl/releases/tag/v0.7.0).
