### ISSUE TITLE
don't ignore config files with json syntax errors

### ISSUE THREAD

**Issue by pitsi** [mvdan/fdroidcl#45]
So, I found fdroidcl a couple of hours ago and I want to use it to install bromite on my phone. Bromite has its own repo for fdroid as seen here
https://www.bromite.org/fdroid

Here are the steps that I followed.
a) I ran `fdroidcl defaults` to make fdroidcl create the ~/.config/fdroidcl/config.json. It worked, and these were its contents
```
$ cat .config/fdroidcl/config.json
{
	"repos": [
		{
			"id": "f-droid",
			"url": "https://f-droid.org/repo",
			"enabled": true
		},
		{
			"id": "f-droid-archive",
			"url": "https://f-droid.org/archive",
			"enabled": false
		}
	]
}
```
b) I added bromite's repo like it is described above, so now the config.json looks like so
```
$ cat .config/fdroidcl/config.json
{
	"repos": [
		{
			"id": "f-droid",
			"url": "https://f-droid.org/repo",
			"enabled": true
		},
		{
			"id": "f-droid-archive",
			"url": "https://f-droid.org/archive",
			"enabled": false
		}
		{
			"id": "bromite",
			"url": "https://fdroid.bromite.org/fdroid/repo",
			"enabled": true
		}
	]
}

```
c) I ran `fdroidcl update` to update the index, but only one of them, the stock one for fdroid was updated/downloaded
```
$ fdroidcl update
Downloading https://f-droid.org/repo/index-v1.jar... done
```
Why?
d) Bromite's repo was obviously not scanned at all, since searching for bromite returns no results. However searching for something else that exists on the main fdroid repo, does return results
```
$ fdroidcl search klar
de.marmaro.krt.ffupdater FFUpdater - 68.3.7 (42)
    Downloader, installer and updater for browsers from Mozilla
org.mozilla.klar         Firefox Klar - 8.0.15 (232)
    Get The Privacy Browser. Fast & always private from Firefox, a browser you trust
```
So what am I doing wrong?
Debian testing x64, fdroidcl 0.5.0 running as a simple user

**Comment by mvdan** [comment]
Did you use that config, exactly? It's invalid JSON. Not sure why the code isn't picking that up.

**Comment by pitsi** [comment]
Well... that is what `fdroidcl defaults` created. I have no idea how to create one :(

**Comment by mvdan** [comment]
I mean your second JSON. You added an extra element to the list, but you forgot a comma.

**Comment by pitsi** [comment]
Can you show me where? Both the url lines for the other repos end in a comma.

**Comment by mvdan** [comment]
Line 12, just like the line 7. If you fix that comma, the config works.

Admittedly, the tool should be showing the syntax error, instead of ignoring the config entirely.

**Comment by pitsi** [comment]
It worked! Thank you very much!
```
$ fdroidcl update
Downloading https://f-droid.org/repo/index-v1.jar... not modified
Downloading https://fdroid.bromite.org/fdroid/repo/index-v1.jar... done

$ fdroidcl search bromite
com.android.webview  Bromite SystemWebView -  (1590883731)
    SystemWebview which contains all Bromite patches; requires root for installation
org.bromite.bromite  Bromite -  (1590883731)
    Bromite is Chromium plus ad blocking and enhanced privacy; take back your browser
org.bromite.chromium Chromium -  (1590883731)
    Vanilla Chromium built side-by-side with Bromite
```

At first, I removed the comma on line 7, thinking it was uneeded, but `fdroidcl update` popped this error
```
$ fdroidcl update
Downloading https://f-droid.org/repo/index-v1.jar... 
update: could not update index: Get https://f-droid.org/repo/index-v1.jar: net/http: TLS handshake timeout
```

**Comment by Linus789** [comment]
The comma on line 7 is needed.

**Comment by pitsi** [comment]
As noted above by @mvdan, the problem is not that I missed the comma but that fdroidcl should point out the error instead of ignoring it and just continuing with the rest of the file. That is why the title was changed, to reflect this (as an) issue.

**Comment by mvdan** [comment]
Yep, indeed `readConfig` ignores json decoding errors. I apparently did that very early on, in bbf402016e01e3bc82f54785a8bbcd957ee03eb2, and cannot remember why. Probably an oversight.

**Comment by Linus789** [comment]
Sorry, missed that part.

**Comment by Linus789** [comment]
Implemented with https://github.com/mvdan/fdroidcl/releases/tag/v0.6.0.

**Comment by pitsi** [comment]
Thank you very much! Until debian updates its package, I have removed it and I will try the binary to test all the changes, once the new version of bromite is released.

**Comment by pitsi** [comment]
Sorry for bringing this back to the surface, but after 2+ years I just added a new repo for cromite
```
{
	"repos": [
		{
			"id": "f-droid",
			"url": "https://f-droid.org/repo",
			"enabled": true
		},
		{
			"id": "f-droid-archive",
			"url": "https://f-droid.org/archive",
			"enabled": false
		},
		{
			"id": "bromite",
			"url": "https://fdroid.bromite.org/fdroid/repo",
			"enabled": false
		}
		{
			"id": "cromite",
			"url": "https://uazo.codeberg.page/cromite-static/@pages/fdroid/repo",
			"enabled": true
		}
	]
}
```
and frdoidcl update fails with this error
```
$ fdroidcl update
config /home/user/.config/fdroidcl/config.json: invalid character '{' after array element
```
Removing the 5 lines for the repo makes fdroidcl work again, so what am I doing wrong? Could it be the @ character in the url?

**Comment by Linus789** [comment]
First of all, you could simply use `$ fdroidcl repo add <NAME> <URL>` instead of editing the file manually. You are missing a comma after the bromite repository.

**Comment by pitsi** [comment]
You are right. In fact, it is the exact same issue as the one I mentioned at the start. I will try the repo function next time.
