### ISSUE TITLE
Feature request: Can you please add a progress bar?

### ISSUE THREAD

**Issue by pitsi** [mvdan/fdroidcl#46]
I made my first installation/upgrade earlier on bromite with fdroidcl and it worked perfectly as you can see from its output below.
```
$ fdroidcl install org.bromite.bromite
Downloading https://fdroid.bromite.org/fdroid/repo/rel_83.0.4103.101_arm64_ChromeModernPublic.apk... done
Installing org.bromite.bromite
```
It took some time to download the apk, since I am on an 8Mbps connection, so I thought it was stuck at first. So, can you please add a progress bar, preferably for both the download and the installation process?

Thank you in advance.

**Comment by mvdan** [comment]
Sure, patches welcome. There are plenty of Go packages to do this kind of thing, such as https://pkg.go.dev/github.com/schollz/progressbar/v3.

**Comment by pitsi** [comment]
I am the wrong guy for the job, because I am really bad at programming.
I would appreciate if someone else could do it and I will do the testing.

**Comment by Linus789** [comment]
Should work now with https://github.com/mvdan/fdroidcl/releases/tag/v0.6.0.
