### ISSUE TITLE
Unable to install VLC: no matching abis

### ISSUE THREAD

**Issue by onny** [mvdan/fdroidcl#5]
```
1 onny@onny ~/projects/android-syssetup % fdroidcl install org.videolan.vlc
Downloading http://f-droid.org/repo/org.videolan.vlc_1090005.apk... not modified
Installing org.videolan.vlc... 
2016/03/25 17:20:37 Could not install org.videolan.vlc: no matching abis
```
Installing VLC via F-Droid works fine ...

Best regards,
Jonas

**Comment by mvdan** [comment]
Note that this is a known missing feature as per the README:

```
Missing features:
[...]
* Device compatibility filters (minSdk, maxSdk, arch, hardware features)
```

**Comment by onny** [comment]
Any way to specifiy this manually?

**Comment by mvdan** [comment]
I'll look into grabbing device info via adb. Surely there's a way to do it.

**Comment by relan** [comment]
I'd also like to see filters implemented, because all my devices have ABI-specific apps that `fdroidcl` cannot upgrade.

> I'll look into grabbing device info via adb. Surely there's a way to do it.

A lot of info can be obtained via `getprop`, e.g.:
```
$ adb shell getprop ro.product.cpu.abi
x86
$ adb shell getprop ro.build.version.sdk
23
```

**Comment by onny** [comment]
Thanks this fixed it!
