### ISSUE TITLE
Version code & name often incorrect - matching spurious other numbers

### ISSUE THREAD

**Issue by OJFord** [mvdan/fdroidcl#51]
Very often the `Package.VersCode` & `Package.VersName` seem to instead parse out the `targetSdk` (I'm seeing a lot of `29`s & `23`s, which matches that value for those packages I've checked) or other odd numbers that aren't the versionCode/versionName.

`VersName` also frequently seems to get the `versionName`, but from a completely different package.

From a glance at the code, the problem seems to be that there's no control that when we write the versions back, we're still in the same `Package` 'section' - since all packages are read at once. I still don't really understand why it goes wrong, since the versions _aren't_ missing.

When I do something similar but reading packages singly `dumpsys package <package>` it works fine:
https://github.com/OJFord/terraform-provider-android/commit/510cf8059af7c0fb77c256df8f62cf9bcb03b19a#diff-fa6ddf3ce4282f3d8869a8556992a65df23f389ef71e94771c6b80e77d9301a3R267-R329

(I'd be happy to work on a patch if I can work out what's going wrong and you're amenable to it.)

**Comment by mvdan** [comment]
With `fdroidcl search -i`, I am unable to reproduce this issue at 4684bbe535147f80898e1e657bcd3cd253c11ec4. How can I reproduce it?

> From a glance at the code, the problem seems to be that there's no control that when we write the versions back, we're still in the same `Package` 'section'

I'm not sure that I understand; look at this code in master:

```
                if m := packageRegex.FindStringSubmatch(l); m != nil {
                        if first {
                                first = false
                        } else {
                                packages[cur.ID] = cur
                                cur = Package{}
                        }
                        cur.ID = m[1]
```

Every time we see a new Package line, we reset the Package struct. So any versions recorded must be after the last Package line and before the next one.

Perhaps you can share the output of `adb shell dumpsys package packages`, and we can try to reproduce from there. With the output I have, I don't seem to get any bugs. Please share the output of `adb version` too; for me, it's:

```
$ adb version
Android Debug Bridge version 1.0.41
Version 30.0.5-6877874
Installed as /opt/android-sdk/platform-tools/adb
```

**Comment by OJFord** [comment]
```
Android Debug Bridge version 1.0.41
Version 30.0.5
Installed as /usr/bin/adb
```

> look at this code in master:

I thought that it must be not matching the package line; so the versions were being set multiple times per `cur.ID`, overwriting the correct ones.

As I write this though, I'm looking again at the code I was using, and I haven't had a coffee yet but I'm pretty sure it's my error, I'm new to/don't write much Go - I was iterating the packages to find a specific package ID, and assigned to a Package pointer when found; I think (now) the `installed_pkg_info` is just changing value (at the same address) each iteration, so since I didn't `break` (for no good reason) it ends up being the last `Package` always?
```go
			pkg := d.Get("name").(string)
			var pkg_info *adb.Package
			for installed_pkg, installed_pkg_info := range installed {
				log.Printf("%s has %s", device.Model, installed_pkg)
				if installed_pkg == pkg {
					pkg_info = &installed_pkg_info
				}
			}
```

Sorry for the noise, will close assuming you agree.

**Comment by mvdan** [comment]
Yes, that is indeed just a bug in your code :) see https://medium.com/golangspec/range-clause-and-the-address-of-iteration-variable-b1796885d2b7
