### ISSUE TITLE
Enhance install -u with ability to exclude an app and jump if error

### ISSUE THREAD

**Issue by Mannshoch** [mvdan/fdroidcl#53]
I dont know why but if I use fdroidcl on a phone I get a `install: could not install net.osmand.plus: exit status 1` this app was bought and installed by Google play. fdroidcl stop on this error and do not proceed further.

Please add an exclude option and also a skip error option to the `install` command.

**Comment by mvdan** [comment]
It would be better to just not suggest upgrading apps which cannot be upgraded. Ideally we'd detect this if the signature is not the same, but if that is not possible, we could perhaps check which apps were installed via other stores.

**Comment by Mannshoch** [comment]
I recently had an interesting case where one app was not able to install. In the result the problem was the size of the app all other were small enough but this one app was too huge to install. Also in this case I got an exit status 1.I had not only to remove files on my device but also to force a media rescan. After that it worked.

**Comment by Linus789** [comment]
Implemented with https://github.com/mvdan/fdroidcl/releases/tag/v0.6.0.

**Comment by Mannshoch** [comment]
Best thanks @Linus789 for your Work  👍
