### ISSUE TITLE
syntax error: unexpected o755, expecting comma or )

### ISSUE THREAD

**Issue by nickrbogdanov** [mvdan/fdroidcl#54]
On Debian Buster and Ubuntu Bionic, golang (1.11 or 1.10) may be too old to support this syntax:

```
$ go get mvdan.cc/fdroidcl
# mvdan.cc/fdroidcl
../go/src/mvdan.cc/fdroidcl/main.go:23:28: syntax error: unexpected o755, expecting comma or )
```

I looked around to see if there was a PPA supported by the Golang project, didn't see anything that seemed official or trustworthy.

**Comment by mvdan** [comment]
The README does say Go 1.14 or later, which came out a year ago. If you can't install a new version of Go, you can also consider an older version of fdroidcl - v0.5.0 requires Go 1.11 or later. Beware that both fdroidcl 0.5.0 and Go 1.11 are unmaintained.
