### ISSUE TITLE
F-Droid Client Problem - IVPN App Installation Version Conflict

### ISSUE THREAD

**Issue by kackle435** [mvdan/fdroidcl#61]
The F-Droid IVPN App shows that i have IVPN 2.8.2 Installed when I have 2.6.0 Installed on my Note 20 Ultra.

i can’t update to the 2.8.2 version because it shows that is is currently installed and when I uninstall IVPN app. The F-Droid Client still shows that i have version 2.8.2 installed.

I cannot resolve this problem. Please fix the F-Droid Client from this bug.

Please view 3 Screenshots from my Note 20 Ultra.

![2022-05-27-16-51-27](https://user-images.githubusercontent.com/84806178/170825237-d213d7cd-9593-4ba1-8395-89fc266777a1.png)

![Screenshot_20220527-165043_F-Droid](https://user-images.githubusercontent.com/84806178/170825241-c28ac79f-97a0-4982-8f4f-7afba5d0f45b.jpg)

![Screenshot_20220527-165048_F-Droid](https://user-images.githubusercontent.com/84806178/170825243-31499511-d913-4781-9cd8-17ec05c36111.jpg)

**Comment by mvdan** [comment]
That last screenshot you posted is the Android F-Droid client, which is different from this one. You want https://gitlab.com/fdroid/fdroidclient.
