### ISSUE TITLE
Debian Bookworm does not install apps

### ISSUE THREAD

**Issue by axet** [mvdan/fdroidcl#63]
Hello!

On debian bookworm I unable to install apps, 'fdroid devices' just freeze and doing nothing. Along as 'fdroid install ...' it just sit and waits forever. 'fdroid devices' crash with the following:

```
fdroidcl devices
devices: could not get devices: failed to get device ABIs
```

'adb devices' or 'adb shell' works.

PS: Also you calling official packages, unofficial for some reason on README.md

**Comment by mhmdanas** [comment]
> PS: Also you calling official packages, unofficial for some reason on README.md

These packages are unofficial as in being maintained by people other than the fdroidcl maintainer(s).

**Comment by axet** [comment]
This is how linux distro works. People take source code and upload it as part of distribution. Since it is opensource you can check if source code, make sue it is unchanged and call them official. This would make more sense, than calling them unofficial == untrusted.

**Comment by mhmdanas** [comment]
That isn't really true, but I don't want to debate such a trivial matter further. :)
