### ISSUE TITLE
fals positive? (Win10/defender Trojan:Script/Wacatac.H!ml)

### ISSUE THREAD

**Issue by MilesTeg97** [mvdan/fdroidcl#66]
MS Win 10 defender reports Trojan:Script/Wacatac.H!ml (serious, can execute code)

Installed fdroidcl via 

`go install mvdan.cc/fdroidcl@latest`

Most probably a false positive. Can so confirm?

**Comment by mvdan** [comment]
Some antivirus companies really don't like Go binaries, perhaps due to the runtime. See https://www.reddit.com/r/golang/comments/r6onxo/has_anyone_found_a_good_antivirus_for_windows/ and many other online threads.
