### ISSUE TITLE
Add support for processing MyAppList backups

### ISSUE THREAD

**Issue by craftyguy** [mvdan/fdroidcl#9]
There's a great app I use to automatically backup a list of installed apps every time an app is added/removed from my device, and it would be AWESOME if your desktop client was able to process a backup file and install the apps onto a device. The flow would be something like this:
1) user uses device with f-droid and MyAppList, adding/removing apps, list of installed apps actively and autmatically created by MyAppList
2) User removes list from device, and wipes data or acquires new device
3) user uses your desktop client to restore apps on the device using the backup list obtained from MyAppList

This would be a good alternative since the f-droid folks seem to be totally against helping folks out (https://gitlab.com/fdroid/fdroidclient/issues/70)

Here's a link to the MyAppList app:
https://f-droid.org/repository/browse/?fdfilter=myapp&fdid=com.projectsexception.myapplist.open

**Comment by mvdan** [comment]
> This would be a good alternative since the f-droid folks seem to be totally against helping folks out 

You do realise it's still me, right? We are not "against" anything. It's an open issue - if it's so important to you, patches are welcome.

As for supporting third party backup formats, I think that's outside the scope of this program. You can feed a list of apps (app ids, aka package names) to `fdroidcl install`, though. So it should be fairly easy to gather the list of apps from whatever format or program you use and feed them to this program.

**Comment by craftyguy** [comment]
Why did you push this app on the fdroid issue 70 if it doesn't do anything to solve the problem?

**Comment by mvdan** [comment]
What I said was:

> you can get a list of installed apps via this alternative F-Droid client

> You can't automate the whole process, but can use it to get the list and later install all the apps at once
